name: Package Classic addon

on:
  push:
    branches:
      - master
    tags:
      - '**-classic'
    paths-ignore:
      - '.github/**'
      - 'ldoc.ltp'

env:
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: LUA Lint
        uses: davidcraig/action-wow-lint@1.0.0
        with:
            path-to-files: 'main.lua'

      - name: Package Classic
        uses: BigWigsMods/packager@master

      - name: Package BC Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g bc
